### ISSUE TITLE
Check Sensor state before reading value

### ISSUE THREAD

**Issue by liquidcronos** [TriPed-Robot/joint_level_control#23]
Requires #22

Since even a faulty SPI connection might produce readable sensor values, it has to be checked that the reading is a valid measurment.
For this purpose the hardware interface read function should first read out the error state of the sensor.

**Comment by Ibidu** [comment]
Done. Depending on specification it is also possible to differentiate between error types.
This is done using the `getErrors()` fct from the underlying hall_sensor class.
The specification of the error bits can be found in the header of the spi transfer file (currently swing_sensor_rosinterface.h)
