### ISSUE TITLE
Add Error State to hardware interface

### ISSUE THREAD

**Issue by liquidcronos** [TriPed-Robot/joint_level_control#24]
Requires #23

If an error is detected as specified in #23 the hardware interface should enter a error state in which it only sends a standart value supplied by a ROS parameter.

**Comment by Ibidu** [comment]
What are the transitions for the error handling state machine?
I presume the states are: `OK` and `ERROR` 

1. Does 1 error suffice to go from OK to ERROR or should it take multiple? 
1.1. if multiple: should the number be a parameter in joints.yaml?
1.2 Should the type of error fall into consideration? (e.g. an SPI Mode error is often occurring and shouldn't affect the data)

2. What are the transitions from ERROR state? 
2.1 Is it possible to recover from ERROR state after x error-less readings?

**Comment by Ibidu** [comment]
Currently a basic implementation is used.
If there is an error, enter ERROR state. If not go from error state to OK.

**Comment by Ibidu** [comment]
New implementation: 
Read errors:
Apply weights to the different error types and sum over them, 
If sum is larger than a threshold: 
>  go into error state and stay there. 

If no errors: 
> have error sum decay (sum -= ...) with 0 as lower bound.
