### ISSUE TITLE
Broadcast hardware interface state as diagnostic message

### ISSUE THREAD

**Issue by liquidcronos** [TriPed-Robot/joint_level_control#25]
Requires  #24 

Since higher level modules rely on the hardware interface it has to broadcasts its state using a diagnostic message.

**Comment by Ibidu** [comment]
What should be part of this message?
Currently it only broadcasts the state of the hardware interface. 
So OK if the state is OK and WARN if some errors occurred.
it also broadcasts the number of errors occurring in a row over the last read accesses.

**Comment by Ibidu** [comment]
Setting up a diagnostic aggregator for human readable diagnostics (e.g. via rqt) might also be a good idea.
The aggregator should operate remotely though, since the BBB lacks compute power.

**Comment by Ibidu** [comment]
Done.
Topic names are now /diagnostics/<joint id>
